import { promises as fs } from 'fs';
import { join } from 'path';
import type { HubFileConfig } from '../config/types.js';

interface KnowledgeFile {
  filename: string;
  title: string;
  summary: string;
}

/**
 * Extract title and summary from a markdown file.
 * Title = first # heading line (stripped of #)
 * Summary = content of the first ## Summary section (first paragraph after it),
 *           or first non-empty paragraph if no Summary section exists.
 */
async function extractMetadata(filePath: string): Promise<{ title: string; summary: string }> {
  const content = await fs.readFile(filePath, 'utf-8');
  const lines = content.split('\n');

  let title = '';
  let summary = '';
  let inSummarySection = false;
  let summaryLines: string[] = [];

  for (const line of lines) {
    if (!title && line.startsWith('# ')) {
      title = line.slice(2).trim();
    }
    if (line.startsWith('## Summary')) {
      inSummarySection = true;
      continue;
    }
    if (inSummarySection) {
      if (line.startsWith('## ')) break; // next section
      if (line.trim()) summaryLines.push(line.trim());
      else if (summaryLines.length > 0) break; // end of paragraph
    }
  }

  summary = summaryLines.join(' ');

  // Fallback: first non-empty non-heading paragraph
  if (!summary) {
    let capturing = false;
    const fallbackLines: string[] = [];
    for (const line of lines) {
      if (!line.startsWith('#') && line.trim()) {
        capturing = true;
        fallbackLines.push(line.trim());
      } else if (capturing && !line.trim()) {
        break;
      }
    }
    summary = fallbackLines.join(' ');
  }

  if (!title) title = 'Untitled';

  return { title, summary: summary.slice(0, 200) };
}

/**
 * Scan knowledge directory and return metadata for all .md files (excluding INDEX.md).
 */
async function scanKnowledgeDir(knowledgeDir: string, indexFile: string): Promise<KnowledgeFile[]> {
  let entries: string[];
  try {
    entries = await fs.readdir(knowledgeDir);
  } catch {
    return []; // dir doesn't exist yet
  }

  const indexBasename = indexFile.split('/').pop() ?? 'INDEX.md';
  const mdFiles = entries.filter(e => e.endsWith('.md') && e !== indexBasename).sort();

  const results: KnowledgeFile[] = [];
  for (const filename of mdFiles) {
    const filePath = join(knowledgeDir, filename);
    const { title, summary } = await extractMetadata(filePath);
    results.push({ filename, title, summary });
  }
  return results;
}

/**
 * Generate the INDEX.md content.
 */
function buildIndexContent(files: KnowledgeFile[], hubName: string): string {
  const lines: string[] = [
    `# ${hubName} — Knowledge Index`,
    '',
    '_Auto-generated by knowhub. Read this first, then explore topic files._',
    '',
    `**${files.length} topic${files.length !== 1 ? 's' : ''}**`,
    '',
  ];

  if (files.length === 0) {
    lines.push('_No knowledge files yet. Run `knowhub absorb` to synthesize your captured learnings._');
  } else {
    for (const file of files) {
      lines.push(`## [${file.title}](${file.filename})`);
      if (file.summary) {
        lines.push('');
        lines.push(file.summary);
      }
      lines.push('');
    }
  }

  lines.push('');
  lines.push(`_Last updated: ${new Date().toISOString().split('T')[0]}_`);

  return lines.join('\n');
}

/**
 * Generate (or regenerate) INDEX.md for the given hub.
 * Returns the path of the written file.
 */
export async function generateIndex(localPath: string, hubFileConfig: HubFileConfig): Promise<string> {
  const knowledgeDir = join(localPath, hubFileConfig.structure.knowledge_dir);
  const indexPath = join(localPath, hubFileConfig.structure.index_file);

  const files = await scanKnowledgeDir(knowledgeDir, hubFileConfig.structure.index_file);
  const content = buildIndexContent(files, hubFileConfig.name);

  await fs.writeFile(indexPath, content, 'utf-8');
  return indexPath;
}
